### ISSUE TITLE
Thanks @Blooket-Council!

### ISSUE THREAD

**Issue by ghost** [Blooket-Council/Blooket-Cheats#1]
Thanks for helping out the cheats. Ive never seen beyound blooket. My personal fav in the GUI.js is getdailyrewards.min. I Just Want to say 'Thank You'

**Comment by buddha-3979** [comment]
i also want to say thank you to you

**Comment by 0005Konzz** [comment]
so do i. but @buddha-3979, you are iligial

**Comment by olivermas** [comment]
the hole time you could of got hacks here https://gitlab.com/blooket/blooket-cheats/-/blob/main/cheats/gui.js?ref_type=heads

**Comment by 05Konzz** [comment]
np

**Comment by 005Konzz** [comment]
thats fine

**Comment by 005Konzz** [comment]
Thanks 005Konzz

**Comment by 005Konzz** [comment]
idea: ban hack: stops you from being banned
