### ISSUE TITLE
QUESTION: What minifier do you use to minify scripts

### ISSUE THREAD

**Issue by SuperBlueEyeBall** [Blooket-Council/Blooket-Cheats#17]
I really need to know this because all minifiers I try break the script.

And also, (I do this and you should too) run the scripts through a URI encoder so character codes don't break things.
Try [this](https://meyerweb.com/eric/tools/dencoder/) website for encoding scripts.
Source code is very simple, its safe.

**Comment by SuperBlueEyeBall** [comment]
[also source code is here](view-source:https://meyerweb.com/eric/tools/dencoder/)

**Comment by 05Konzz** [comment]
I'm pretty sure it's uglify on npm

**Comment by 05Konzz** [comment]
I'll look into it later in the day
