### ISSUE TITLE
IDEA: Crash Game, Freeze Scoreboard, Lobby Chat, and blooket game code guesser cheats

### ISSUE THREAD

**Issue by ASTHEBEST** [Blooket-Council/Blooket-Cheats#18]
### Gamemode

general

### Function

self explanatory. u cud refer to https://github.com/randomstuff69/blooketpluscheats/tree/main too.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by ASTHEBEST** [comment]
also for crypto hack u can add green host's screen and for some gamemodes u can make it so that u can change the text on the action thing to advertise text.

**Comment by 05Konzz** [comment]
I understand your want for those to be implemented here, but since the BC+ devs are friends of ours, they won't be added unless they specifically ask me to.
