### ISSUE TITLE
Is there a website?

### ISSUE THREAD

**Issue by orn8** [Blooket-Council/Blooket-Cheats#2]
When 05Konz's account had the Blooket cheats, they provided a website to easily copy scripts with a friendly GUI, which is now nowhere to be found. Will a website be added in the future or is there already one?

**Comment by 0005Konzz** [comment]
hi @orn8,
you are a massave idiot.

**Comment by orn8** [comment]
thank you for your reply. i have been enlightened by those three words and you have inspired me to find the cure to cancer and settle on mars with my homie elon musk. i am deeply grateful.
