### ISSUE TITLE
Please hack evowars on Crazygames?

### ISSUE THREAD

**Issue by buddha-3979** [Blooket-Council/Blooket-Cheats#4]
People can hack blooket but can't hack evowars on crazygames, why?

**Comment by buddha-3979** [comment]
People can hack blooket but can't hack evowars on crazygames, why?

**Comment by buddha-3979** [comment]
People can hack blooket but can't hack evowars on crazygames, why?

**Comment by buddha-3979** [comment]
People can hack blooket but can't hack evowars on crazygames, why?

**Comment by zastlx** [comment]
because we don't want to, stop opening issues for this

**Comment by TheAmazingAceLeo** [comment]
> because we don't want to, stop opening issues for this

finally someone with some sense

**Comment by Collusionz** [comment]
> People can hack blooket but can't hack evowars on crazygames, why?

WHAT THE FK IS EVOWARS

**Comment by buddha-3979** [comment]
Please

**Comment by buddha-3979** [comment]
I ask you to help me hack evowars, please. I sincerely beg you. I beg you

**Comment by Githubman6996** [comment]
If you want them so badly do it yourself

**Comment by TheAmazingAceLeo** [comment]
@buddha-3979 ![image](https://github.com/user-attachments/assets/5ac60e74-378d-496e-b3a1-e0c2462a7fad)

**Comment by buddha-3979** [comment]
I'm so sorry. I will close this issue. Please don't report me
