### ISSUE TITLE
so i got suspended.

### ISSUE THREAD

**Issue by ghost** [Blooket-Council/Blooket-Cheats#8]
_No description Provided_

**Comment by BiddoRules** [comment]
i dont think there is anyway out of it, I got banned before and missed half of spooky season

**Comment by GamerDog7456** [comment]
got banned until 2026 :D

**Comment by BlooketCommunity** [comment]
Oh no,
I got ban ending 2 days

**Comment by ZackiBoiz** [comment]
see this is why you don't skid
